# Generated by Django 5.2.13 on 2026-05-28 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Q


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0002_initial"),
        ("reviews", "0002_review_moderation_fields"),
        ("stores", "0004_store_review_count"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("target_type", models.CharField(choices=[("review", "Review"), ("product", "Product"), ("store", "Store")], max_length=16)),
                ("reason", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("status", models.CharField(choices=[("open", "Open"), ("resolved", "Resolved"), ("rejected", "Rejected")], db_index=True, default="open", max_length=16)),
                ("handled_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("handled_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="handled_reports", to=settings.AUTH_USER_MODEL)),
                ("product", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="reports", to="products.product")),
                ("reporter", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="reports", to=settings.AUTH_USER_MODEL)),
                ("review", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="reports", to="reviews.review")),
                ("store", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="reports", to="stores.store")),
            ],
            options={
                "db_table": "reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="report",
            constraint=models.CheckConstraint(
                name="report_exactly_one_target",
                check=(
                    (Q(review__isnull=False) & Q(product__isnull=True) & Q(store__isnull=True))
                    | (Q(review__isnull=True) & Q(product__isnull=False) & Q(store__isnull=True))
                    | (Q(review__isnull=True) & Q(product__isnull=True) & Q(store__isnull=False))
                ),
            ),
        ),
    ]

