# Generated by Django 5.2.13 on 2026-04-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(help_text='Запрос пользователя')),
                ('response', models.TextField(help_text='Ответ ИИ')),
                ('context_products', models.JSONField(blank=True, help_text='ID товаров, использованных в контексте', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI Chat History',
                'verbose_name_plural': 'AI Chat Histories',
                'db_table': 'ai_chat_history',
            },
        ),
    ]
