# Generated by Django 5.2.13 on 2026-05-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aichathistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'AI Chat Entry', 'verbose_name_plural': 'AI Chat History'},
        ),
        migrations.AddField(
            model_name='aichathistory',
            name='applied_filters',
            field=models.JSONField(blank=True, help_text="Извлечённые фильтры: {max_price: 3000, category: 'ванна'}", null=True),
        ),
        migrations.AddField(
            model_name='aichathistory',
            name='completion_tokens',
            field=models.IntegerField(default=0, help_text='Токены ответа (выход)'),
        ),
        migrations.AddField(
            model_name='aichathistory',
            name='prompt_tokens',
            field=models.IntegerField(default=0, help_text='Токены запроса (вход)'),
        ),
        migrations.AddField(
            model_name='aichathistory',
            name='response_type',
            field=models.CharField(choices=[('search', 'Поиск товаров'), ('recommendation', 'AI-рекомендация'), ('fallback', 'Нет результатов / Уточнение'), ('transactional', 'Оформление заказа / Статус')], default='search', max_length=20),
        ),
        migrations.AddField(
            model_name='aichathistory',
            name='total_tokens',
            field=models.IntegerField(default=0, help_text='Суммарный расход'),
        ),
        migrations.AlterField(
            model_name='aichathistory',
            name='context_products',
            field=models.JSONField(blank=True, help_text='Сериализованные товары для сайдбара (id, name, price, image, quick_add)', null=True),
        ),
        migrations.AlterField(
            model_name='aichathistory',
            name='response',
            field=models.TextField(help_text='Текстовый ответ LLM'),
        ),
    ]
