# Generated by Django 5.2.13 on 2026-05-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0003_alter_aichathistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aichathistory',
            name='applied_filters',
            field=models.JSONField(blank=True, help_text="Extracted filters, for example: {max_price: 3000, category: 'bathroom'}", null=True),
        ),
        migrations.AlterField(
            model_name='aichathistory',
            name='completion_tokens',
            field=models.IntegerField(default=0, help_text='Completion tokens'),
        ),
        migrations.AlterField(
            model_name='aichathistory',
            name='context_products',
            field=models.JSONField(blank=True, help_text='Serialized products for sidebar cards (id, name, price, image, quick_add)', null=True),
        ),
        migrations.AlterField(
            model_name='aichathistory',
            name='prompt_tokens',
            field=models.IntegerField(default=0, help_text='Prompt tokens'),
        ),
        migrations.AlterField(
            model_name='aichathistory',
            name='query',
            field=models.TextField(help_text='User message'),
        ),
        migrations.AlterField(
            model_name='aichathistory',
            name='response',
            field=models.TextField(help_text='LLM text response'),
        ),
        migrations.AlterField(
            model_name='aichathistory',
            name='response_type',
            field=models.CharField(choices=[('search', 'Product Search'), ('recommendation', 'AI Recommendation'), ('fallback', 'No Results / Clarification'), ('transactional', 'Checkout / Status')], default='search', max_length=20),
        ),
        migrations.AlterField(
            model_name='aichathistory',
            name='total_tokens',
            field=models.IntegerField(default=0, help_text='Total tokens used'),
        ),
    ]
