# Generated by Django 5.2.13 on 2026-05-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Bank Card'), ('sbp', 'SBP'), ('cash', 'Cash on Delivery')], default='card', max_length=10),
        ),
    ]
